require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::CompositionsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Composition. As you add validations to Admin::Composition, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all admin_compositions as @admin_compositions" do
      composition = Admin::Composition.create! valid_attributes
      get :index
      assigns(:admin_compositions).should eq([composition])
    end
  end

  describe "GET show" do
    it "assigns the requested composition as @composition" do
      composition = Admin::Composition.create! valid_attributes
      get :show, :id => composition.id.to_s
      assigns(:composition).should eq(composition)
    end
  end

  describe "GET new" do
    it "assigns a new composition as @composition" do
      get :new
      assigns(:composition).should be_a_new(Admin::Composition)
    end
  end

  describe "GET edit" do
    it "assigns the requested composition as @composition" do
      composition = Admin::Composition.create! valid_attributes
      get :edit, :id => composition.id.to_s
      assigns(:composition).should eq(composition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Composition" do
        expect {
          post :create, :composition => valid_attributes
        }.to change(Admin::Composition, :count).by(1)
      end

      it "assigns a newly created composition as @composition" do
        post :create, :composition => valid_attributes
        assigns(:composition).should be_a(Admin::Composition)
        assigns(:composition).should be_persisted
      end

      it "redirects to the created composition" do
        post :create, :composition => valid_attributes
        response.should redirect_to(Admin::Composition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved composition as @composition" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Composition.any_instance.stub(:save).and_return(false)
        post :create, :composition => {}
        assigns(:composition).should be_a_new(Admin::Composition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Composition.any_instance.stub(:save).and_return(false)
        post :create, :composition => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested composition" do
        composition = Admin::Composition.create! valid_attributes
        # Assuming there are no other admin_compositions in the database, this
        # specifies that the Admin::Composition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Composition.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => composition.id, :composition => {'these' => 'params'}
      end

      it "assigns the requested composition as @composition" do
        composition = Admin::Composition.create! valid_attributes
        put :update, :id => composition.id, :composition => valid_attributes
        assigns(:composition).should eq(composition)
      end

      it "redirects to the composition" do
        composition = Admin::Composition.create! valid_attributes
        put :update, :id => composition.id, :composition => valid_attributes
        response.should redirect_to(composition)
      end
    end

    describe "with invalid params" do
      it "assigns the composition as @composition" do
        composition = Admin::Composition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Composition.any_instance.stub(:save).and_return(false)
        put :update, :id => composition.id.to_s, :composition => {}
        assigns(:composition).should eq(composition)
      end

      it "re-renders the 'edit' template" do
        composition = Admin::Composition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Composition.any_instance.stub(:save).and_return(false)
        put :update, :id => composition.id.to_s, :composition => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested composition" do
      composition = Admin::Composition.create! valid_attributes
      expect {
        delete :destroy, :id => composition.id.to_s
      }.to change(Admin::Composition, :count).by(-1)
    end

    it "redirects to the admin_compositions list" do
      composition = Admin::Composition.create! valid_attributes
      delete :destroy, :id => composition.id.to_s
      response.should redirect_to(admin_compositions_url)
    end
  end

end
