development:
  adapter: mysql2
  database: pianodb_dev
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: pianodb_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: pianodb_prod
  username: root
  pool: 5
  timeout: 5000
